/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yjj_utils_JDiff */

#ifndef _Included_yjj_utils_JDiff
#define _Included_yjj_utils_JDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yjj_utils_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
    JNIEXPORT jint JNICALL Java_com_yjj_utils_DiffUtils_genDiff
      (JNIEnv *, jclass, jstring, jstring, jstring);

/*
   * Class:     com_yjj_utils_PatchUtils
   * Method:    patch
   * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
   */
    JNIEXPORT jint JNICALL Java_com_yjj_utils_DiffUtils_patch
      (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
